# Generated by Django 6.1.1 on 2026-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanelog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
