# Generated by Django 6.1.1 on 2026-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0002_lanelog_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_ssid', models.CharField(max_length=100)),
                ('wifi_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TurnStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('center', 'Center'), ('side', 'Side'), ('differently_abled', 'Differently Abled')], max_length=30)),
                ('placement', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('flip', 'Flip')], max_length=10)),
                ('entry_pin', models.IntegerField()),
                ('exit_pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lane',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lane',
            name='model',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='lane',
            name='turnstyles',
            field=models.ManyToManyField(related_name='lanes', to='speedlaneapp.turnstyle'),
        ),
    ]
