# Generated by Django 6.1.1 on 2026-09-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0004_rename_make_lane_created_by_remove_lane_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='lane',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='turnstyle',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='turnstyle',
            name='modified_by',
        ),
    ]
