# Generated by Django 6.1.1 on 2026-09-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0005_remove_lane_modified_at_remove_lane_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lane',
            name='width',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='lane',
            name='lane_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanegroup', to='speedlaneapp.lanegroup'),
        ),
    ]
