# Generated by Django 6.1.1 on 2026-09-22 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0006_lanegroup_lane_width_lane_lane_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='trigger_delay',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='lane',
            name='lane_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='speedlaneapp.lanegroup'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='wifi_password',
            field=models.CharField(default='Abcd123', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='wifi_ssid',
            field=models.CharField(default='Abaci', max_length=100),
        ),
    ]
