# Generated by Django 6.1.1 on 2026-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0007_systemconfig_trigger_delay_alter_lane_lane_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnstyle',
            name='entry_pin',
        ),
        migrations.RemoveField(
            model_name='turnstyle',
            name='exit_pin',
        ),
        migrations.AddField(
            model_name='lane',
            name='entry_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lane',
            name='exit_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
