# Generated by Django 6.1.1 on 2026-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0008_remove_turnstyle_entry_pin_remove_turnstyle_exit_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
