# Generated by Django 6.1.1 on 2026-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0009_alter_systemconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanegroup',
            name='emergency_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lanegroup',
            name='fire_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
