# Generated by Django 6.1.1 on 2026-09-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0010_lanegroup_emergency_pin_lanegroup_fire_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='lane_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanegroup_logs', to='speedlaneapp.lanegroup'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='type',
            field=models.CharField(choices=[('fire', 'Fire'), ('emergency', 'Emergency'), ('normal', 'Normal')], default='normal', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lane_logs', to='speedlaneapp.lane'),
        ),
    ]
