# Generated by Django 6.1.1 on 2026-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0011_accesslog_lane_group_accesslog_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='wifi_password',
            field=models.CharField(default='Abcd@123', max_length=255),
        ),
    ]
