# Generated by Django 6.1.1 on 2026-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0012_alter_systemconfig_wifi_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanegroup',
            name='emergency_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lanegroup',
            name='fire_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
