# Generated by Django 6.1.1 on 2026-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0013_alter_lanegroup_emergency_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='entry_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lane',
            name='exit_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
