# Generated by Django 6.1.1 on 2026-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedlaneapp', '0014_alter_lane_entry_pin_alter_lane_exit_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='delay',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
    ]
